language: go

go:
  - 1.14.x
  - 1.13.x
  - master
os:
  - linux
matrix:
 fast_finish: true
 allow_failures:
   - go: master

env:
  global:
    - GO_ENV=test
    - GO111MODULE=on
    - GOMODCACHE=/home/travis/gopath/pkg/mod

services:
  - postgresql

before_script:
  - ./buffalo db create -a
  - ./buffalo db migrate
  - ./buffalo t db:setup
  - mkdir -p $TRAVIS_BUILD_DIR/public/assets
  - go get github.com/gobuffalo/suite

go_import_path: github.com/go-saloon/saloon

install:
  - go get -v ./...
  - go build -o ./buffalo $GOMODCACHE/github.com/gobuffalo/buffalo@v0.11.1-0.20180329210144-44948b8981b1/buffalo

script: ./buffalo test
